config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'
Rails.application.routes.draw do
  mount Sidekiq::Web =>'/sidekiq'

  root 'main#home'
  match '/404', to: 'errors#not_found', via: :all, as: :not_found
  match '/500', to: 'errors#internal_server_error', via: :all, as: :internal_server_error
  get 'info_detail/:id/:type', to: 'main#info_detail', as: :info_detail
  get 'cities/district/:id', to: 'cities#show_district', as: 'district'
  get 'cities/ward/:id', to: 'cities#show_ward', as: 'ward'
  get '/contacts', to: 'contacts#new'
  post '/contacts', to: 'contacts#create'
  get 'search', to: 'main#search', as: :search

  devise_for :users, controllers: {
    registrations: 'registrations',
    sessions:      'sessions',
    passwords:     'passwords'
  }

  resources :charts, only: %i[index], constraints: { year: /\d{4}/, month: /\d{1,2}/, quarter: /\d{1}/ }

  resources :company_types
  resources :business_areas
  resources :newly_established
  resources :status
  resources :cities
  resources :tax_code_personal do
    collection do
      get 'search', to: 'tax_code_personal#search', as: :search_person
    end
  end

  namespace :admin do
    root to: 'base#index'
    get 'districts_by_city', to: 'districts#districts_by_city'
    get 'wards_by_district', to: 'wards#wards_by_district'

    resources :company_types, only: %i[index]
    resources :represents
    resources :contacts, only: %i[index show edit update destroy]

    resources :companies do
      collection do
        get 'search', to: 'companies#search', as: :search_company
      end
    end

    resources :people do
      collection do
        get :search, to: 'people#search', as: :search_person
      end
    end

    resources :tax_codes do
      collection do
        get :company_options
        get :person_options
        get 'search', to: 'tax_codes#search', as: :search_tax_code
      end
    end

    resources :business_areas do
      collection do
        get 'search', to: 'business_areas#search', as: :search_business_are
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/business_area.rb
class BusinessArea < ApplicationRecord
  has_many :companies, dependent: :nullify
  validates :name, presence: { message: 'Please Business Area name cannot be blank' }, uniqueness: true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :districts, dependent: :destroy
  has_many :companies, dependent: :destroy
  has_many :people, dependent: :destroy

  validates :name, presence: true
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :represent
  belongs_to :city
  belongs_to :district
  belongs_to :ward
  belongs_to :company_type
  belongs_to :business_area, optional: true
  belongs_to :status
  has_one :tax_code, as: :taxable, dependent: :destroy

  validates :name, :address, :managed_by, :date_start, presence: true
end

app/models/company_type.rb
class CompanyType < ApplicationRecord
  has_many :companies, dependent: :nullify
  has_many :people, dependent: :nullify
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, :email, :content, presence: true
end

app/models/district.rb
class District < ApplicationRecord
  belongs_to :city
  has_many :wards, dependent: :destroy
  has_many :companies, dependent: :destroy
  has_many :people, dependent: :destroy
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :city
  belongs_to :district
  belongs_to :ward
  belongs_to :company_type
  belongs_to :status
  has_one :tax_code, as: :taxable, dependent: :destroy

  validates :cmnd, uniqueness: { scope: :cmnd, if: -> { cmnd.present? } }
  validates :name, :address, :managed_by, :date_start, presence: true
end

app/models/represent.rb
class Represent < ApplicationRecord
  has_many :companies, dependent: :destroy
  validates :name, presence: true
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :companies, dependent: :nullify
  has_many :people, dependent: :nullify
end

app/models/tax_code.rb
class TaxCode < ApplicationRecord
  belongs_to :taxable, polymorphic: true
  validates :code, uniqueness: true, presence: true
  validates :taxable_type, :taxable_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/ward.rb
class Ward < ApplicationRecord
  belongs_to :district
  has_many :companies, dependent: :destroy
  has_many :people, dependent: :destroy
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :prepare_cities, only: %i[home info_detail search]

  def home
    data_company = Company.order('RANDOM()').includes(:represent, :tax_code, :city, :district, :ward).limit(10)
    data_person = Person.order('RANDOM()').includes(:tax_code, :city, :district, :ward).limit(10)
    @data = (data_company + data_person).shuffle
  end

  def search
    query = params[:q]&.strip&.downcase
    city_id = params[:city_id]
    @results = []

    if query.present?
      company_results = Company
        .left_joins(:represent, :tax_code)
        .where("LOWER(companies.name) LIKE ? OR LOWER(represents.name) LIKE ? OR COALESCE(tax_codes.code, '') LIKE ?", "%#{query}%", "%#{query}%", "%#{query}%")
        .includes(:tax_code, :represent, :city, :district, :ward)
      person_results = Person
        .left_joins(:tax_code)
        .where("LOWER(people.name) LIKE ? OR LOWER(people.cmnd) LIKE ? OR COALESCE(tax_codes.code, '') LIKE ?", "%#{query}%", "%#{query}%", "%#{query}%")

      @results = company_results + person_results
    end

    @results = @results.select { |result| city_id.blank? || result.city_id == city_id.to_i }

    @pagy, @paginated_results = pagy_array(@results)

    if @results.count == 1
      result = @results.first
      type = result.class.name.downcase
      redirect_to info_detail_path(id: result.id, type:)
    else
      render 'search_results'
    end
  end

  def info_detail
    @new_companies = Company
      .where('date_start >= ?', 20.days.ago)
      .order(date_start: :desc)
      .includes(:represent, :tax_code, :city, :district, :ward)
    @new_persons = Person
      .where('date_start >= ?', 20.days.ago)
      .order(date_start: :desc)
      .includes(:tax_code, :city, :district, :ward)

    @pagy, @new_entity = pagy_array(@new_companies + @new_persons)

    type = params[:type]
    id = params[:id]

    case type
    when 'company'
      @entity = Company.find(id)

      @related_companies_ward = Company
        .where(ward_id: @entity.ward_id)
        .includes(:tax_code, :represent, :city, :district, :ward)
        .order('RANDOM()')
        .limit(5)

      @related_companies_district = Company
        .where(district_id: @entity.district_id)
        .includes(:tax_code, :represent, :city, :district, :ward)
        .order('RANDOM()')
        .limit(5)

      @related_companies_city = Company
        .where(city_id: @entity.city_id)
        .includes(:tax_code, :represent, :city, :district, :ward)
        .order('RANDOM()')
        .limit(5)

      @related_wards = Ward.where(district_id: @entity.district_id)

      @breadcrumb_data = [
        { name: 'Tra cứu mã số thuế', path: root_path },
        { name: @entity.name, path: info_detail_path(id: @entity.id, type: 'company') }
      ]
    when 'person'
      @entity = Person.find(id)
    end

    @breadcrumb_data = [
      { name: 'Tra cứu mã số thuế', path: root_path },
      { name: @entity.name, path: info_detail_path(id: @entity.id, type: 'person') }
    ]
  end

  private

  def prepare_cities
    @cities = City.order(:id)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
  def render_turbo_stream_flash_messages
    turbo_stream.prepend 'flash', partial: 'layouts/flash'
  end
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/status_helper.rb
module StatusHelper
end

app/views/main/_list_business_area.slim
- if @entity.business_area.present?
  .container[style='padding-top: 40px']
    h1
      | Ngành nghề kinh doanh
    table.table
      thead
        th[colspan=2]
          | Ngành
      tbody
        tr
          td
            | Tên
          td
            - if @entity.business_area.present?
              = link_to @entity.business_area.name, business_area_path(@entity.business_area), class: "nav-link fw-bold"
              - if @entity.business_area.detail.present?
                | Chi tiết: 
                = @entity.business_area.detail

app/views/main/_list_city.slim
.container[style='padding-top: 40px']
  h1
    | Tra cứu mã số thuế và danh sách công ty tại 
    = @entity.city.name
  .list-type
    ul
      - @related_companies_city.each do |company|
        .content
          h4
            = link_to company.name, info_detail_path(id: company.id, type: 'company'), class: "content-name"
          strong #
          | Mã số thuế: 
          = link_to company.tax_code&.code.to_s, info_detail_path(id: company.id, type: 'company'), class: "text-decoration-none text-dark"
          br
          strong
            i.fa-solid.fa-person 
          |  Người đại diện: 
          = company.represent&.name || ''
          br
          strong
            i.fa-solid.fa-location-dot 
          = full_address(company)
          hr

app/views/main/_list_company.slim
- @data.each do |category|
  .content
    h4
      = link_to category.name, info_detail_path(id: category.id, type: category.class.name.downcase), class: "content-name"
    strong #
    | Mã số thuế: 
    = link_to category.tax_code&.code.to_s, info_detail_path(id: category.id, type: category.class.name.downcase), class: "text-decoration-none text-dark"
    br
    strong
      i.fa-solid.fa-person 
    |  Người đại diện: 
    = category.instance_of?(Company) && category.represent&.name || category.name
    br
    strong
      i.fa-solid.fa-location-dot 
    = full_address(category)
    hr

app/views/main/_list_district.slim
.container[style='padding-top: 40px']
  h1
    | Tra cứu mã số thuế và danh sách công ty tại 
    = @entity.district.name
  .list-type
    ul
      - @related_companies_district.each do |company|
        .content
          h4
            = link_to company.name, info_detail_path(id: company.id, type: 'company'), class: "content-name"
          strong #
          | Mã số thuế: 
          = link_to company.tax_code&.code.to_s, info_detail_path(id: company.id, type: 'company'), class: "text-decoration-none text-dark"
          br
          strong
            i.fa-solid.fa-person 
          |  Người đại diện: 
          = company.represent&.name || ''
          br
          strong
            i.fa-solid.fa-location-dot 
          = full_address(company)
          hr

app/views/main/_list_newly_established.slim
.container[style='padding-top: 40px']
  h1
    | Tra cứu mã số thuế và danh sách công ty mới thành lập
  .list-type
    ul
      - @new_entity.each do |category|
        .content
          h4
            = link_to category.name, info_detail_path(id: category.id, type: category.class.name.downcase), class: "content-name"
          strong #
          | Mã số thuế: 
          = link_to category.tax_code&.code.to_s, info_detail_path(id: category.id, type: category.class.name.downcase), class: "text-decoration-none text-dark"
          br
          strong
            i.fa-solid.fa-person 
          |  Người đại diện: 
          = category.instance_of?(Company) ? category.represent.name : category.name
          br
          strong
            i.fa-solid.fa-location-dot 
          = full_address(category)
          hr
  == pagy_bootstrap_nav(@pagy)

app/views/main/_list_ward.slim
.container[style='padding-top: 40px']
  h1
    | Tra cứu mã số thuế và danh sách công ty tại 
    = @entity.ward.name
  .list-type
    ul
      - @related_companies_ward.each do |company|
        .content
          h4
            = link_to company.name, info_detail_path(id: company.id, type: 'company'), class: "content-name"
          strong #
          | Mã số thuế: 
          = link_to company.tax_code&.code.to_s, info_detail_path(id: company.id, type: 'company'), class: "text-decoration-none text-dark"
          br
          strong
            i.fa-solid.fa-person 
          |  Người đại diện: 
          = company.represent.name if company.represent.present?
          br
          strong
            i.fa-solid.fa-location-dot 
          = full_address(company)
          hr

app/views/main/_sidebar_city.slim
  h5 
    | Tỉnh thành phố
  - @cities.each do |city|
    ul
      li
        = link_to city_path(city), class: "city-item" do
          i.fa-solid.fa-chevron-right.fa-2xs
          = city.name

app/views/main/_sidebar_ward.slim
h5
  = @entity.city.name+ ' - '+ @entity.district.name
- @related_wards.each do |ward|
  ul
    li
      = link_to ward_path(ward), class: "city-item" do
        i.fa-solid.fa-chevron-right.fa-2xs
        = ward.name

app/views/main/home.slim
#carouselExampleCaptions.carousel.slide[data-bs-ride="carousel" data-bs-touch="true"]
  .carousel-indicators
    button.active[type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" aria-current="true" aria-label="Slide 1"]
    button[type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"]
    button[type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"]
    button[type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="3" aria-label="Slide 4"]
  .carousel-inner
    .carousel-item.active
      img.d-block.w-100[src="https://masothue.com/assets/images/slider/xtra-cuu-ma-so-thue-slide-2-min.png.pagespeed.ic.2zJHIHv0aL.webp" alt=""]
      .carousel-caption.d-none.d-md-block.content-slider
        h5
          | Tra cứu mã số thuế cá nhân
        h1
          | Tra cứu 
          strong mã số thuế cá nhân 
          br
          |nhanh chóng tiện lợi
    .carousel-item
      img.d-block.w-100[src="https://masothue.com/assets/images/slider/xtra-cuu-ma-so-thue-slide-4-min.png.pagespeed.ic.sjYy5mDY40.webp" alt="..."]
      .carousel-caption.d-none.d-md-block.content-slider
        h5
          | Tin Tức
        h1
          | Về thuế, kế toán và doanh nghiệp 
          br 
          strong Thông tin mới nhất
    .carousel-item
      img.d-block.w-100[src="https://masothue.com/assets/images/slider/xtra-cuu-ma-so-thue-slide-3-min.png.pagespeed.ic.YweYEEDKnI.webp" alt="Third slide"]
      .carousel-caption.d-none.d-md-block.content-slider
        h5
          | Tra cứu mã số thuế
        h1
          | Tra cứu trực tiếp ngay trên  
          br 
          strong Facebook & Zalo
    .carousel-item
      img.d-block.w-100[src="https://masothue.com/assets/images/slider/xtra-cuu-ma-so-thue-slide-4-min.png.pagespeed.ic.sjYy5mDY40.webp" alt="four slide"]
      .carousel-caption.d-none.d-md-block.content-slider
        h5
          | Tra cứu mã số thuế công ty
        h1
          | Hơn 
          strong 1,7 triệu 
          | doanh nghiệp trên
          br
          | 63 tỉnh thành
.container
  .row.info-home
    .feature-list.d-flex.justify-content-around.align-item-center.border.p-5.rounded-3
      .media.d-flex.align-items-center[style="font-size: 20px;"]
        .media-left
          i.fa-solid.fa-rotate-left[style="font-size: 30px; color:red;"]
        .media-body.ps-4.text-center
          strong
            | Cập nhật
          br
          |  liên tục 
      .media.d-flex.align-items-center[style="font-size: 20px;"]
        .media-left
          i.fa-regular.fa-thumbs-up.fa-lg[style="font-size: 30px; color:red;"]
        .media-body.ps-4.text-center
          strong
            | Thông tin
          br
          |  chính xác 
      .media.d-flex.align-items-center[style="font-size: 20px;"]
        .media-left
          i.fa-solid.fa-phone[style="font-size: 30px; color:red;"]
        .media-body.ps-4.text-center
          strong
            | Hỗ trợ
          br
          |  đa nền tảng 
      .media.d-flex.align-items-center[style="font-size: 20px;"]
        .media-left
          i.fa-solid.fa-building[style="font-size: 30px; color:red;"]
        .media-body.ps-4.text-center
          strong
            | 1,7 triệu
          br
          |  doanh nghiệp 
      .media.d-flex.align-items-center[style="font-size: 20px;"]
        .media-left
          i.fa-solid.fa-location-dot[style="font-size: 30px; color:red;"]
        .media-body.ps-4.text-center
          strong
            | 63 tỉnh
          br
          |  Thành phố 
.content-area.container.pt-5
  .area-section
    h1
      | Tra Cứu Mã Số Thuế (Công ty, Cá nhân)
    = render partial: 'list_company'
  .sidebar-blog
    h6 
      | Tra cứu mã số thuế trên facebook
    img src="https://masothue.com/assets/images/xfacebook-masothue.vn.png.pagespeed.ic.eTS6GzZSmp.webp" alt="Search Taxcode on Facebook"/
    = render partial: 'sidebar_city'

app/views/main/info_detail.slim
= render 'shared/breadcrumb'
.content-area.container.pt-4
  .area-section
    h1
      = @entity.tax_code&.code.to_s + '-' + @entity.name.upcase
    table.table.mt-4
      thead
        th[colspan=2]
          = @entity.name.upcase
      tbody
        - if @entity.instance_of?(Company)
          tr
            td
              i.fa.fa-globe.fa-xs.pe-2
              | Tên quốc tế
            td
              = @entity.name.upcase
          - if @entity.sub_name.present?    
            tr
              td
                i.fa.fa-reorder.fa-xs.pe-2
                | Tên viết tắt
              td
                = @entity.sub_name.upcase
        tr
          td
            i.fa.fa-hashtag.fa-xs.pe-2
            | Mã số thuế
          td
            = @entity.tax_code&.code
        tr
          td
            i.fa-solid.fa-location-dot.fa-xs.pe-2
            | Địa chỉ
          td
            = full_address(@entity)
        tr
          td
            i.fa.fa-user.fa-xs.pe-2
            | Người đại diện
          td
            = @entity.instance_of?(Company) && @entity.represent&.name || @entity.name

        tr
          td
            i.fa.fa-phone.fa-xs.pe-2
            | Điện thoại
          td
            = @entity.phone_number
        tr
          td
            i.fa.fa-calendar.fa-xs.pe-2
            | Ngày hoạt động
          td
            = @entity.date_start
        tr
          td
            i.fa.fa-users.fa-xs.pe-2
            | Quản lý bởi
          td
            = @entity.managed_by
        tr 
          td
            i.fa.fa-building.fa-xs.pe-2
            | Loại hình DN
          td
            = @entity.company_type.type_name
        - if @entity.status.name.present?     
          tr 
            td
              i.fa.fa-info.fa-xs.pe-2
              | Tình trạng
            td
              = @entity.status.name
    i Thông tin mã số thuế  #{@entity.tax_code&.code} được cập nhật lần cuối #{@entity.updated_at}.
    - if @entity.instance_of?(Company)
      = render partial: 'list_business_area'
      = render partial: 'list_ward'
      = render partial: 'list_district'
      = render partial: 'list_city'
    = render partial: 'list_newly_established'

  .sidebar-blog
    h6 
      | Tra cứu mã số thuế trên facebook
    img src="https://masothue.com/assets/images/xfacebook-masothue.vn.png.pagespeed.ic.eTS6GzZSmp.webp" alt="Search Taxcode on Facebook"/
    - if @entity.instance_of?(Person)
      = render partial: 'sidebar_city'
    - elsif @entity.instance_of?(Company)
      = render partial: 'sidebar_ward'
    
    

app/views/main/search_results.slim
.content-area.container[style='padding-top: 40px']
  .area-section
    h1
      | Kết quả tìm kiếm cho "#{params[:q]}"
    .filter-select
      = form_tag search_path, method: :get do
        = text_field_tag :q, params[:q], class: "d-none", type: 'search', aria_label: 'Search'
        = select_tag :city_id, options_for_select([["Lọc theo Tỉnh/Thành Phố", ""]] + @cities.pluck(:name, :id), params[:city_id]), class: 'form-select', onchange: 'this.form.submit()'
    - if @paginated_results.present?
      table.table
        tbody
        - @paginated_results.each do |result|
          - if params[:city_id].blank? || (result.respond_to?(:city_id) && result.city_id == params[:city_id].to_i)
            .content
              h4
                = link_to result.name, info_detail_path(id: result.id, type: result.class.name.downcase), class: "content-name"
              strong #
              | Mã số thuế: 
              = link_to result.tax_code&.code.to_s, info_detail_path(id: result.id, type: result.class.name.downcase), class: "text-decoration-none text-dark"
              br
              strong
                i.fa-solid.fa-person 
              |  Người đại diện: 
              = result.instance_of?(Company) ? result.represent.name : result.name
              br
              strong
                i.fa-solid.fa-location-dot 
              = full_address(result)
              hr
      == pagy_bootstrap_nav(@pagy)
    - else
      p Không tìm thấy kết quả theo yêu cầu!
  .sidebar-blog
    h6 
      | Tra cứu mã số thuế trên facebook
    img src="https://masothue.com/assets/images/xfacebook-masothue.vn.png.pagespeed.ic.eTS6GzZSmp.webp" alt="Search Taxcode on Facebook"
    = render partial: 'sidebar_city'