config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'
Rails.application.routes.draw do
  mount Sidekiq::Web =>'/sidekiq'

  root 'main#home'
  match '/404', to: 'errors#not_found', via: :all, as: :not_found
  match '/500', to: 'errors#internal_server_error', via: :all, as: :internal_server_error
  get 'info_detail/:id/:type', to: 'main#info_detail', as: :info_detail
  get 'cities/district/:id', to: 'cities#show_district', as: 'district'
  get 'cities/ward/:id', to: 'cities#show_ward', as: 'ward'
  get '/contacts', to: 'contacts#new'
  post '/contacts', to: 'contacts#create'
  get 'search', to: 'main#search', as: :search

  devise_for :users, controllers: {
    registrations: 'registrations',
    sessions:      'sessions',
    passwords:     'passwords'
  }

  resources :charts, only: %i[index], constraints: { year: /\d{4}/, month: /\d{1,2}/, quarter: /\d{1}/ }

  resources :company_types
  resources :business_areas
  resources :newly_established
  resources :status
  resources :cities
  resources :tax_code_personal do
    collection do
      get 'search', to: 'tax_code_personal#search', as: :search_person
    end
  end

  namespace :admin do
    root to: 'base#index'
    get 'districts_by_city', to: 'districts#districts_by_city'
    get 'wards_by_district', to: 'wards#wards_by_district'

    resources :company_types, only: %i[index]
    resources :represents
    resources :contacts, only: %i[index show edit update destroy]

    resources :companies do
      collection do
        get 'search', to: 'companies#search', as: :search_company
      end
    end

    resources :people do
      collection do
        get :search, to: 'people#search', as: :search_person
      end
    end

    resources :tax_codes do
      collection do
        get :company_options
        get :person_options
        get 'search', to: 'tax_codes#search', as: :search_tax_code
      end
    end

    resources :business_areas do
      collection do
        get 'search', to: 'business_areas#search', as: :search_business_are
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/business_area.rb
class BusinessArea < ApplicationRecord
  has_many :companies, dependent: :nullify
  validates :name, presence: { message: 'Please Business Area name cannot be blank' }, uniqueness: true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :districts, dependent: :destroy
  has_many :companies, dependent: :destroy
  has_many :people, dependent: :destroy

  validates :name, presence: true
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :represent
  belongs_to :city
  belongs_to :district
  belongs_to :ward
  belongs_to :company_type
  belongs_to :business_area, optional: true
  belongs_to :status
  has_one :tax_code, as: :taxable, dependent: :destroy

  validates :name, :address, :managed_by, :date_start, presence: true
end

app/models/company_type.rb
class CompanyType < ApplicationRecord
  has_many :companies, dependent: :nullify
  has_many :people, dependent: :nullify
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, :email, :content, presence: true
end

app/models/district.rb
class District < ApplicationRecord
  belongs_to :city
  has_many :wards, dependent: :destroy
  has_many :companies, dependent: :destroy
  has_many :people, dependent: :destroy
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :city
  belongs_to :district
  belongs_to :ward
  belongs_to :company_type
  belongs_to :status
  has_one :tax_code, as: :taxable, dependent: :destroy

  validates :cmnd, uniqueness: { scope: :cmnd, if: -> { cmnd.present? } }
  validates :name, :address, :managed_by, :date_start, presence: true
end

app/models/represent.rb
class Represent < ApplicationRecord
  has_many :companies, dependent: :destroy
  validates :name, presence: true
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :companies, dependent: :nullify
  has_many :people, dependent: :nullify
end

app/models/tax_code.rb
class TaxCode < ApplicationRecord
  belongs_to :taxable, polymorphic: true
  validates :code, uniqueness: true, presence: true
  validates :taxable_type, :taxable_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/ward.rb
class Ward < ApplicationRecord
  belongs_to :district
  has_many :companies, dependent: :destroy
  has_many :people, dependent: :destroy
end

app/controllers/admin/tax_codes_controller.rb
class Admin::TaxCodesController < Admin::BaseController
  before_action :fetch_taxable_types, only: %i[new create]

  OBJECT_TAXCODE = %w[Company Person].freeze

  def search
    authorize TaxCode
    query = params[:q]&.strip&.downcase
    @pagy, @tax_codes = pagy_array([])

    @tax_codes = TaxCode.where('tax_codes.code LIKE ? ', "%#{query}%").includes(taxable: %i[represent city district ward]) if query.present?

    if @tax_codes.blank?
      render 'no_result'
    else
      render 'index'
    end
  end

  def index
    authorize TaxCode
    tax_codes = TaxCode.includes(taxable: %i[represent city district ward]).all
    tax_codes = tax_codes.where(taxable_type: params[:taxable_type]) if params[:taxable_type].present?
    @pagy, @tax_codes = pagy(tax_codes, items: 10)
  end

  def company_options
    @taxable_objects = Company.where.not(id: TaxCode.where(taxable_type: 'Company').pluck(:taxable_id))
    render json: @taxable_objects
  end

  def person_options
    @taxable_objects = Person.where.not(id: TaxCode.where(taxable_type: 'Person').pluck(:taxable_id))
    render json: @taxable_objects
  end

  def new
    authorize TaxCode
    @tax_code = TaxCode.new
  end

  def create
    tax_code_params_stripped = taxcode_params
    tax_code_params_stripped[:code].strip! if tax_code_params_stripped[:code].present?
    @tax_code = TaxCode.new(tax_code_params_stripped)
    authorize @tax_code
    if @tax_code.save
      respond_to do |format|
        format.html { redirect_to admin_tax_codes_path, notice: 'Tax Code was successfully created!' }
        format.turbo_stream
      end
    else
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tax_code = TaxCode.find(params[:id])
    authorize @tax_code
    @tax_code.destroy
    redirect_to admin_tax_codes_path, status: :see_other, notice: 'Tax Code was successfully deleted!'
  end

  private

  def fetch_taxable_types
    @taxable_types = OBJECT_TAXCODE
  end

  def render_taxable_objects
    render json: @taxable_objects
  end

  def taxcode_params
    params.require(:tax_code).permit(
      :code,
      :taxable_type,
      :taxable_id
    )
  end
end

app/helpers/admin/tax_codes_helper.rb
module Admin::TaxCodesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
  def render_turbo_stream_flash_messages
    turbo_stream.prepend 'flash', partial: 'layouts/flash'
  end
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/status_helper.rb
module StatusHelper
end

app/views/admin/tax_codes/_form.slim
.row.mb-3 
  .col 
    = f.input :code, label: "Tax Code", input_html: { class: 'form-control'}, placeholder: "Tax Code"
.row.mb-3 
  .col 
    = f.input :taxable_type, require: true, label: "Type", prompt: "Select Type", collection: @taxable_types, input_html: { class: 'form-control', id: 'tax-code-taxable-type' }
  .col
    = f.input :taxable_id, collection: [], label_method: :name, value_method: :id, prompt: 'Please Choose Type', input_html: {id: 'tax-code-taxable-id'}
= link_to "Back", admin_tax_codes_path, class: "sub-back-button btn btn-secondary float-start"
= f.button :submit, value: "Submit", class: "sub-back-button btn btn-primary float-end", data: {turbo: false}

app/views/admin/tax_codes/_header.slim
.add-style
  = link_to admin_tax_codes_path, class: 'cursor-pointer text-dark' do
    h3 
      strong.text-danger Tax Code 
      | Management

  = form_tag search_tax_code_admin_tax_codes_path, method: :get, class: 'd-flex style-search', role: 'search' do
    = text_field_tag :q, params[:q], class: 'form-control me-2', type: 'search', placeholder: 'Search Tax Code...', aria_label: 'Search'
    button.btn.btn-dark(type="submit")
      i.fas.fa-search
      
  .filter-select
    = form_tag admin_tax_codes_path, method: :get do
      = text_field_tag :q, params[:q], class: "d-none", type: 'search', aria_label: 'Search'
      = select_tag :taxable_type, options_for_select([["Lọc theo loại", ""]] + [["Company", "Company"], ["Person", "Person"]], params[:taxable_type]), class: 'form-select', onchange: 'this.form.submit()'

  i.note-text 
    |"Each company or individual has only an tax code, which cannot be changed"
  = link_to new_admin_tax_code_path, class: 'btn cursor-pointer button_add btn-primary', type: 'button' do
    i.fa-solid.fa-plus.me-2
    |  Add Tax Code 

app/views/admin/tax_codes/index.slim
#flash.flash
  = render "layouts/flash"
.body-content  
  = render partial: 'header'
  .p-3.content-table
    table.table.table-hover.align-middle.mb-0.bg-white.table-responsive.table-bordered.shadow
      thead.bg-light
        tr
          th[style="width: 30px"]
            | STT
          th[style="width: 90px"]
            | #Tax Code
          th
            | Name
          th[style="width: 130px"]
            | Represent
          th[style="width: 200px"]
            | Address
          th[style="width: 60px"]
            | Type
          th[style="width: 25px"]
      tbody
      - @tax_codes.each_with_index do |taxcode, index|
        - taxable = taxcode.taxable
        tr
          td
            = index + 1
          td
            strong
              = taxcode.code
          td
            .d-flex.align-items-center
              div
                p.fw-bold.mb-1
                  = taxable.name
                p.text-muted.mb-0
                  = taxable.is_a?(Company) ? taxable.sub_name : ''
          td
            = taxable.is_a?(Company) && taxable.represent&.name || taxable.name
          td 
            = full_address(taxable)
          td
            = taxcode.taxable_type
          td
            = button_to admin_tax_code_path(taxcode), method: :delete, data: { turbo_confirm: 'Are you sure?' }, data: {turbo: false}, class: "btn btn-link-dark btn-sm", role: "button" do 
              i.fa.fa-trash
  == pagy_bootstrap_nav(@pagy)

app/views/admin/tax_codes/new.slim
.body-content
  h3.taxcode-title
    | New Tax Code 
  .taxcode-form.rounded-4.shadow.bg-body.rounded.border-1
    .style-form-new
      = simple_form_for @tax_code, url: admin_tax_codes_path(@tax_code), method: :post, html: { id: 'tax-code-form' } do |f|
        = render 'form',  tax_code: @tax_code, f:f

app/views/admin/tax_codes/no_result.slim
.body-content
  = render partial: 'header'
  p.ps-3.pt-3.text-danger
    | Not found any search results "#{params[:q]}"