config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'
Rails.application.routes.draw do
  mount Sidekiq::Web =>'/sidekiq'

  root 'main#home'
  match '/404', to: 'errors#not_found', via: :all, as: :not_found
  match '/500', to: 'errors#internal_server_error', via: :all, as: :internal_server_error
  get 'info_detail/:id/:type', to: 'main#info_detail', as: :info_detail
  get 'cities/district/:id', to: 'cities#show_district', as: 'district'
  get 'cities/ward/:id', to: 'cities#show_ward', as: 'ward'
  get '/contacts', to: 'contacts#new'
  post '/contacts', to: 'contacts#create'
  get 'search', to: 'main#search', as: :search

  devise_for :users, controllers: {
    registrations: 'registrations',
    sessions:      'sessions',
    passwords:     'passwords'
  }

  resources :charts, only: %i[index], constraints: { year: /\d{4}/, month: /\d{1,2}/, quarter: /\d{1}/ }

  resources :company_types
  resources :business_areas
  resources :newly_established
  resources :status
  resources :cities
  resources :tax_code_personal do
    collection do
      get 'search', to: 'tax_code_personal#search', as: :search_person
    end
  end

  namespace :admin do
    root to: 'base#index'
    get 'districts_by_city', to: 'districts#districts_by_city'
    get 'wards_by_district', to: 'wards#wards_by_district'

    resources :company_types, only: %i[index]
    resources :represents
    resources :contacts, only: %i[index show edit update destroy]

    resources :companies do
      collection do
        get 'search', to: 'companies#search', as: :search_company
      end
    end

    resources :people do
      collection do
        get :search, to: 'people#search', as: :search_person
      end
    end

    resources :tax_codes do
      collection do
        get :company_options
        get :person_options
        get 'search', to: 'tax_codes#search', as: :search_tax_code
      end
    end

    resources :business_areas do
      collection do
        get 'search', to: 'business_areas#search', as: :search_business_are
      end
    end
  end
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :represent
  belongs_to :city
  belongs_to :district
  belongs_to :ward
  belongs_to :company_type
  belongs_to :business_area, optional: true
  belongs_to :status
  has_one :tax_code, as: :taxable, dependent: :destroy

  validates :name, :address, :managed_by, :date_start, presence: true
end

app/models/company_type.rb
class CompanyType < ApplicationRecord
  has_many :companies, dependent: :nullify
  has_many :people, dependent: :nullify
end

app/controllers/admin/companies_controller.rb
class Admin::CompaniesController < Admin::BaseController
  before_action :prepare_data, only: %i[new create edit update]
  before_action :prepare_company, only: %i[edit update destroy show]
  before_action :prepare_data_filter, only: %i[index search]

  def search
    authorize Company
    query = params[:q]&.strip&.downcase
    @companies = []

    if query.present?
      @companies = Company
        .left_joins(:tax_code, :represent)
        .includes(:tax_code, :represent, :city, :district, :ward)
        .where("LOWER(companies.name) LIKE ? OR LOWER(represents.name) LIKE ? OR COALESCE(tax_codes.code, '') LIKE ?", "%#{query}%", "%#{query}%", "%#{query}%")
    end

    @pagy, @companies = pagy_array(@companies, items: 10)

    if @companies.blank?
      render 'no_result'
    else
      render 'index'
    end
  end

  def index
    authorize Company
    companies = Company.includes(:tax_code, :represent, :city, :district, :ward).all
    companies = companies.where(city_id: params[:city_id]) if params[:city_id].present?
    companies = companies.where(status_id: params[:status_id]) if params[:status_id].present?
    @companies = companies.order(created_at: :asc)
    @pagy, @companies = pagy(@companies, items: 10)
  end

  def show
    authorize Company
    redirect_to admin_company_path if @company.nil?
  end

  def new
    authorize Company
    @company = Company.new
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.update(
          dom_id(@company), partial: 'form', locals: { company: @company }
        )
      end
      format.html
    end
  end

  def create
    @company = Company.new(company_params)
    authorize @company
    if @company.save
      respond_to do |format|
        format.html { redirect_to admin_companies_path, notice: 'Company was successfully created!' }
        format.turbo_stream { flash.now[:notice] = 'Company was successfully created!' }
      end
    else
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
    authorize @company
  end

  def update
    authorize @company
    if @company.update(company_params)
      respond_to do |format|
        format.html { redirect_to admin_companies_path, notice: 'Company was successfully updated!' }
        format.turbo_stream { flash.now[:notice] = 'Company was successfully updated!' }
      end
    else
      respond_to do |format|
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @company
    @company.destroy
    respond_to do |format|
      format.html { redirect_to admin_companies_path, status: :see_other, notice: 'Company was successfully deleted!' }
      format.turbo_stream { flash.now[:notice] = 'Company was successfully deleted!' }
    end
  end

  private

  def prepare_data
    @city_list = City.pluck(:name, :id)
    @represent_list = Represent.pluck(:name, :id)
    @company_type_list = CompanyType.pluck(:type_name, :id)
    @status_list = Status.pluck(:name, :id)
    @business_area_list = BusinessArea.pluck(:name, :id)
  end

  def prepare_company
    @company = Company.find(params[:id])
  end

  def prepare_data_filter
    @cities = City.order(:id)
    @status_list = Status.pluck(:name, :id)
  end

  def company_params
    params.require(:company).permit(
      :name,
      :sub_name,
      :address,
      :date_start,
      :phone_number,
      :managed_by,
      :city_id,
      :district_id,
      :ward_id,
      :company_type_id,
      :business_area_id,
      :represent_id,
      :status_id
    )
  end
end

app/helpers/admin/companies_helper.rb
module Admin::CompaniesHelper
end

app/views/admin/companies/_company.slim
= turbo_frame_tag company do 
  .list-companies.d-flex
    = link_to admin_company_path(company), data: { turbo_frame: "_top" }, class: "nav-link", role: "button" do 
      h6
        strong 
          = company.name
    h6
      strong
        = company.tax_code&.code || 'Chưa có MST'
    h6
      = company.represent.name 
    h6.address-style
      = full_address(company)
    .form-icon
      .icon-item
        = link_to admin_company_path(company), data: { turbo_frame: "_top" }, class: "btn btn-link-info text-danger btn-sm btn-rounded", role: "button" do 
          i.fa.solid.fa-info.btn-info
      .icon-item
        = link_to edit_admin_company_path(company), data: { turbo_frame: dom_id(company) }, class: "btn btn-link btn-sm btn-rounded", role: "button" do 
          i.fa.solid.fa-pen-to-square
      .icon-item
        = button_to admin_company_path(company), method: :delete, data: { turbo_confirm: 'Are you sure delete company?' }, class: "btn btn-link-dark btn-sm btn-rounded", role: "button" do
          i.fa.fa-trash

app/views/admin/companies/_form.slim
.row.mb-3
  .col 
      = f.input :name, required: true, lable: "Name Company",  input_html: {class: 'form-control'}, placeholder: "Name"
  .col 
      = f.input :sub_name, lable: "Sub Name", input_html: {class: 'form-control'}, placeholder: "Sub-name"
  .col 
      = f.input :date_start,lable: "Date Start", start_year: Date.today.year - 50,
                end_year: Date.today.year,order: [:day, :month, :year], input_html: { class: 'form-control'}, label_html: { class: 'style-date' }
.row.mb-3 
  .col 
      = f.input :phone_number, required: true,  input_html: {class: 'form-control'}, placeholder: "Phone number"
  .col 
      = f.input :managed_by, input_html: {class: 'form-control'}, placeholder: "Managed by"
  .col 
      = f.input :address, label: "Address", input_html: {class: 'form-control'},placeholder: "Address Detail"

.row.mb-3
  .col 
    = f.association :city, required: true, prompt: "City", label: "City", collection: @city_list, input_html: { id: "city-select", data: { controller: "dropdown"} }
  .col 
    = f.association :district, required: true, prompt: "District", label: "District", collection: [], input_html: { id: "district-select", data: { controller: "dropdown"} }
  .col 
    = f.association :ward, required: true, prompt: "Ward", label: "Ward", collection: [], input_html: {id: "ward-select" }

.row.mb-3
  .col 
      = f.association :status, required: true, prompt: "Status ", label: "Status", collection: @status_list
  .col
      = f.association :company_type, required: true, prompt: "Company Type", label: "Company Type", collection: @company_type_list

.row.mb-3 
  .col 
      = f.association :represent, required: true, prompt: "Repersent ", label: "Repersent", collection: @represent_list
  .col.style-link-new
      = link_to "New Create Represent", new_admin_represent_path, data: { turbo_frame: dom_id(Company.new) }
  .col 
      = f.association :business_area, prompt: "Business Area ", label: "Business Area", collection: @business_area_list
  .col.style-link-new
      = link_to "New Create Business Areas", new_admin_business_area_path, data: { turbo_frame: dom_id(Company.new) }
  
= link_to "Back", admin_companies_path, class: "sub-back-button btn btn-secondary float-start", target: "_top"
= f.button :submit, value:"Submit", class: "sub-back-button btn btn-primary float-end"

app/views/admin/companies/_header.slim
.add-style
  = link_to admin_companies_path, class: 'cursor-pointer text-dark' do
    h3 
      strong.text-danger Company 
      | Management 
  = form_tag search_company_admin_companies_path, method: :get, class: 'd-flex', style: 'height: 40px', role: 'search' do
    = text_field_tag :q, params[:q], class: 'form-control me-2', style: 'width: 450px; ', type: 'search', placeholder: 'Search...', aria_label: 'Search'
    button.btn.btn-dark(type="submit")
      i.fas.fa-search
      
  .filter-select
    = form_tag admin_companies_path, method: :get do
      = text_field_tag :q, params[:q], class: "d-none", type: 'search', aria_label: 'Search'
      = select_tag :city_id, options_for_select([["Lọc theo tỉnh, thành", ""]] + @cities.pluck(:name, :id), params[:city_id]), class: 'form-select', onchange: 'this.form.submit()'
  
  .filter-select
    = form_tag admin_companies_path, method: :get do
      = text_field_tag :q, params[:q], class: "d-none", type: 'search', aria_label: 'Search'
      = select_tag :status_id, options_for_select([["Lọc theo Trạng thái", ""]] + @status_list, params[:status_id]), class: 'form-select', onchange: 'this.form.submit()'

  = link_to new_admin_company_path, class: 'btn cursor-pointer button_add btn-primary', data: { turbo_frame: dom_id(Company.new) }, type: 'button' do
    i.fa-solid.fa-plus.me-2
    |  Add Company 

app/views/admin/companies/create.turbo_stream.slim
= turbo_stream.prepend "companies", partial: "company", locals: { company: @company }
= turbo_stream.update Company.new, ""
= render_turbo_stream_flash_messages 

app/views/admin/companies/destroy.turbo_stream.slim
= turbo_stream.remove dom_id(@company)
= render_turbo_stream_flash_messages 

app/views/admin/companies/edit.slim
.body-content
  h3.style-form
    | Edit Company 
  = turbo_frame_tag dom_id(@company) do
    .container-form.rounded-4.shadow.bg-body.rounded.border-1
      .style-form-new
        = simple_form_for @company, url: admin_company_path(@company), method: :put do |f|
          = render 'form', company: @company, f:f

app/views/admin/companies/index.slim
= turbo_stream_from "companies"
#flash.flash
  = render "layouts/flash"
.body-content
  = render partial: 'header'
  = turbo_frame_tag 'new_company'
  = turbo_frame_tag "companies" do
    = render @companies
    == pagy_bootstrap_nav(@pagy)

app/views/admin/companies/new.slim
= render 'shared/flash'
.body-content
  = turbo_frame_tag 'new_company' do 
    h3.style-form
      | New Company 
    .container-form.rounded-4.shadow.bg-body.rounded.border-1
      .style-form-new
        = simple_form_for @company, url: admin_companies_path(@company), method: :post do |f|
          = render 'form', company: @company, f:f
    

app/views/admin/companies/no_result.slim
.body-content
  = render partial: 'header'
  p.ps-3.pt-3.text-danger
    | Not found any search results "#{params[:q]}"

app/views/admin/companies/show.slim
.body-content
  h3.pb-4.fw-bold.detail-title
    | THÔNG TIN CHI TIẾT
  .content-details.row
    .col
      p
        | Mã số thuế 
      = @company.tax_code&.code || 'Chưa có MST'
    .col 
      p
        | Tên công ty
      = @company.name
    .col 
      p
        | Tên viết tắt
      = @company.sub_name
    .col 
      p
        | Người đại diện
      = @company.represent.name
    .col 
      p
        | Ngày HD
      = @company.date_start
    .col
      p
        | Quản lý bởi 
      = @company.managed_by
    .col 
      p
        | Trạng thái 
      = @company.status.name
    .col 
      p
        | Số điện thoại
      = @company.phone_number
    .col
      p
        | Loại hình DN
      = @company.company_type&.type_name
    .col
      p
        | Loại ngành nghề
      = @company.business_area&.name
    .col 
      p
        | Địa chỉ
      = full_address(@company) 
= link_to "Back", admin_companies_path, class: "sub-back-button btn btn-secondary float-start"

app/views/admin/companies/update.turbo_stream.slim
= turbo_stream.replace dom_id(@company), partial: "company", locals: { company: @company }
= turbo_stream.update Company.new, ""
= render_turbo_stream_flash_messages 