config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'
Rails.application.routes.draw do
  mount Sidekiq::Web =>'/sidekiq'

  root 'main#home'
  match '/404', to: 'errors#not_found', via: :all, as: :not_found
  match '/500', to: 'errors#internal_server_error', via: :all, as: :internal_server_error
  get 'info_detail/:id/:type', to: 'main#info_detail', as: :info_detail
  get 'cities/district/:id', to: 'cities#show_district', as: 'district'
  get 'cities/ward/:id', to: 'cities#show_ward', as: 'ward'
  get '/contacts', to: 'contacts#new'
  post '/contacts', to: 'contacts#create'
  get 'search', to: 'main#search', as: :search

  devise_for :users, controllers: {
    registrations: 'registrations',
    sessions:      'sessions',
    passwords:     'passwords'
  }

  resources :charts, only: %i[index], constraints: { year: /\d{4}/, month: /\d{1,2}/, quarter: /\d{1}/ }

  resources :company_types
  resources :business_areas
  resources :newly_established
  resources :status
  resources :cities
  resources :tax_code_personal do
    collection do
      get 'search', to: 'tax_code_personal#search', as: :search_person
    end
  end

  namespace :admin do
    root to: 'base#index'
    get 'districts_by_city', to: 'districts#districts_by_city'
    get 'wards_by_district', to: 'wards#wards_by_district'

    resources :company_types, only: %i[index]
    resources :represents
    resources :contacts, only: %i[index show edit update destroy]

    resources :companies do
      collection do
        get 'search', to: 'companies#search', as: :search_company
      end
    end

    resources :people do
      collection do
        get :search, to: 'people#search', as: :search_person
      end
    end

    resources :tax_codes do
      collection do
        get :company_options
        get :person_options
        get 'search', to: 'tax_codes#search', as: :search_tax_code
      end
    end

    resources :business_areas do
      collection do
        get 'search', to: 'business_areas#search', as: :search_business_are
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/business_area.rb
class BusinessArea < ApplicationRecord
  has_many :companies, dependent: :nullify
  validates :name, presence: { message: 'Please Business Area name cannot be blank' }, uniqueness: true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :districts, dependent: :destroy
  has_many :companies, dependent: :destroy
  has_many :people, dependent: :destroy

  validates :name, presence: true
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :represent
  belongs_to :city
  belongs_to :district
  belongs_to :ward
  belongs_to :company_type
  belongs_to :business_area, optional: true
  belongs_to :status
  has_one :tax_code, as: :taxable, dependent: :destroy

  validates :name, :address, :managed_by, :date_start, presence: true
end

app/models/company_type.rb
class CompanyType < ApplicationRecord
  has_many :companies, dependent: :nullify
  has_many :people, dependent: :nullify
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, :email, :content, presence: true
end

app/models/district.rb
class District < ApplicationRecord
  belongs_to :city
  has_many :wards, dependent: :destroy
  has_many :companies, dependent: :destroy
  has_many :people, dependent: :destroy
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :city
  belongs_to :district
  belongs_to :ward
  belongs_to :company_type
  belongs_to :status
  has_one :tax_code, as: :taxable, dependent: :destroy

  validates :cmnd, uniqueness: { scope: :cmnd, if: -> { cmnd.present? } }
  validates :name, :address, :managed_by, :date_start, presence: true
end

app/models/represent.rb
class Represent < ApplicationRecord
  has_many :companies, dependent: :destroy
  validates :name, presence: true
end

app/models/status.rb
class Status < ApplicationRecord
  has_many :companies, dependent: :nullify
  has_many :people, dependent: :nullify
end

app/models/tax_code.rb
class TaxCode < ApplicationRecord
  belongs_to :taxable, polymorphic: true
  validates :code, uniqueness: true, presence: true
  validates :taxable_type, :taxable_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/ward.rb
class Ward < ApplicationRecord
  belongs_to :district
  has_many :companies, dependent: :destroy
  has_many :people, dependent: :destroy
end

app/helpers/admin/shared_helper.rb
module Admin::SharedHelper
  def full_address(addressable)
    address_parts = addressable.address.split(',')
    district_name = addressable.district&.name
    ward_name = addressable.ward&.name
    city_name = addressable.city&.name

    if district_name.nil? || ward_name.nil? || city_name.nil?
      district_name = addressable.district&.name || District.find_by(id: addressable.district_id)&.name
      ward_name = addressable.ward&.name || Ward.find_by(id: addressable.ward_id)&.name
      city_name = addressable.city&.name || City.find_by(id: addressable.city_id)&.name
    end

    if address_parts.size >= 4
      "#{address_parts[0]}, #{address_parts[1..].join(', ')}"
    else
      "#{addressable.address}, #{ward_name}, #{district_name}, #{city_name}, Việt Nam"
    end
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/status_helper.rb
module StatusHelper
end

app/views/shared/_breadcrumb.slim
.breadcrumb.container
  - @breadcrumb_data.each_with_index do |crumb, index|
    - if index == @breadcrumb_data.size - 1
      = crumb[:name]
    - else
      = link_to crumb[:name], crumb[:path]
    - if index < @breadcrumb_data.size - 1
      span
        |  >

app/views/shared/_flash.slim
- if flash[:notice]
    #success-alert.alert.alert-success.alert-dismissible.fade.show.position-fixed.bottom-0.end-0.m-1[role="alert"]
      = flash[:notice]
      button.btn-close[type="button" data-bs-dismiss="alert" aria-label="Close"]

app/views/shared/_footer.slim
footer.text-center.text-white[style="background-color: #f1f1f1;"]
  .container.p-2
    section
      = link_to '#!', class: 'btn btn-outline-dark btn-floating m-3', role: 'button' do
        i.fab.fa-facebook-f
      = link_to '#!', class: 'btn btn-outline-dark btn-floating m-3', role: 'button' do
        i.fab.fa-twitter
      = link_to '#!', class: 'btn btn-outline-dark btn-floating m-3', role: 'button' do
        i.fab.fa-google
      = link_to '#!', class: 'btn btn-outline-dark btn-floating m-3', role: 'button' do
        i.fab.fa-instagram
      = link_to '#!', class: 'btn btn-outline-dark btn-floating m-3', role: 'button' do
        i.fab.fa-linkedin-in
      = link_to '#!', class: 'btn btn-outline-dark btn-floating m-3', role: 'button' do
        i.fab.fa-github

footer.text-center.text-lg-start.bg-white.text-muted
  section
    .container.text-center.text-md-start.mt-5
      .row.mt-3
        .col-md-3.col-lg-4.col-xl-3.mx-auto.mb-4[style='font-size:14px']
          = link_to root_path, class: "navbar-brand" do
            = image_tag image_path("logo/logo.png"), alt: "logo-taxcode" 
          p[style='padding-top: 15px']
            | Trang web giúp bạn tra cứu mã số thuế cá nhân, doanh nghiệp nhanh nhất, chính xác nhất !
          p 
            | Email: info@taxcode.com
          h6.text-uppercase.fw-bold.mb-4[style='color: #DC3545; font-size:14px']
            |  Cảm ơn bạn đã sử dụng dịch vụ của chúng tôi 
        .col-md-2.col-lg-2.col-xl-2.mx-auto.mb-4[style='font-size:14px']
          p
            = link_to business_areas_path, class: "nav-link" do
              | Tra cứu mã số thuế theo ngành nghề
          p
            = link_to company_types_path, class: "nav-link" do
              | Tra cứu mã số thuế theo loại hình doanh nghiệp
          p
            = link_to status_index_path, class: "nav-link" do
              | Tra cứu mã số thuế theo tình trạng DN
        .col-md-3.col-lg-2.col-xl-2.mx-auto.mb-4[style='font-size:14px']
          p
            = link_to "#!", class: "nav-link" do
              | Tra cứu mã số thuế cá nhân
          p
            = link_to newly_established_index_path, class: "nav-link" do
              | Doanh nghiệp mới thành lập
          p
            = link_to cities_path, class: "nav-link" do
              | Mã số thuế theo tỉnh thành phố
        .col-md-4.col-lg-3.col-xl-3.mx-auto.mb-md-0.mb-4[style='font-size:14px']
          h6.text-uppercase.fw-bold.mb-4
            | Chính sách
          p
            i.fas.fa-home.me-3.text-secondary
            |  Quyền riêng tư
          p
            i.fas.fa-envelope.me-3.text-secondary
            |  Điều khoản sử dụng
          p
            i.fas.fa-phone.me-3.text-secondary
            |  Liên hệ
  .text-center.p-4
    |  © 2023 Copyright: 
    = link_to root_path, class: "text-reset fw-bold text-decoration-none" do
      | TaxCodeInfo

app/views/shared/_header.html.erb
<div class="container">
  <div class="row">
    <nav class="navbar navbar-expand-lg">
      <div class="container-fluid">
        <a class="navbar-brand", style="font-size: small;" href="/">Tra cứu mã số thuế công ty, mã số thuế cá nhân</a>
        <!-- <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button> -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
            </li>
          </ul>
          <i class="fa-solid fa-location-dot"></i>
          <ul class="navbar-nav">
            <li class="nav-item" style="font-size: 16px"> 
              <%= link_to "Tỉnh/Thành phố ", cities_path, class: "nav-link"%>
            </li>
            <% if current_user %>
              <li class="nav-item"> <%= link_to "Edit Account", edit_user_registration_path, class: "nav-link" %></li>
              <li class="nav-item"> <%= button_to "Sign Out", destroy_user_session_path, method: :delete, data: {turbo: false}, class: "btn btn-small btn-dark mx-2" %></li>
            <% else %>
              <%= link_to "|   Tra cứu mã số thuế cá nhân", tax_code_personal_index_path, class: "nav-link"%>
            <% end %>
          </ul>
        </div>
      </div>  
    </nav>
  </div>
</div>

app/views/shared/_header_dashboard.slim
      
  nav#main-navbar.navbar.navbar-expand-lg.navbar-light.fixed-top.header-dashboard
    .container-fluid
      a.navbar-brand[href="/admin/tax_codes"]
        = image_tag "logo/logo_admin.png", height: "45", alt: "logo-taxcode", loading: "lazy", style: "padding-left: 27px;"
      h3.fw-bold.text-light Tax Code Management System
      ul.navbar-nav
        - if current_user
          li.nav-item
            = link_to "Edit Account", edit_user_registration_path, class: "nav-link text-light"
          li.nav-item
            = button_to "Sign Out", destroy_user_session_path, method: :delete, data: {turbo: false}, class: "btn btn-small btn-light mx-2"
        - else
          li.nav-item
            = link_to "Sign Up", new_user_registration_path, class: "nav-link"
          li.nav-item
            = link_to "Sign In", new_user_session_path, class: "btn btn-small border-dark rounded-3 btn-light mx-2"